#!/bin/bash
# Renew Let's Encrypt SSL certificates using acme-tiny
# Version 1.6 (build 20200919)
#
# Copyright (c) 2016-2021  Daniel Rudolf <www.daniel-rudolf.de>
#
# This work is licensed under the terms of the MIT license.
# For a copy, see LICENSE file or <https://opensource.org/licenses/MIT>.
#
# SPDX-License-Identifier: MIT
# License-Filename: LICENSE

APP_NAME="$(basename "$0")"
set -e

VERSION="1.6"
BUILD="20200919"

if [ ! -d "/etc/ssl/acme" ]; then
    echo "$APP_NAME: Base directory '/etc/ssl/acme' not found" >&2
    exit 1
elif [ ! -x "$(which acme-issue)" ]; then
    echo "$APP_NAME: 'acme-issue' executable not found" >&2
    exit 1
fi

function showUsage() {
    echo "Usage:"
    echo "  $APP_NAME --all"
    echo "  $APP_NAME DOMAIN_NAME..."
}

# read parameters
VERBOSE="no"
DOMAINS=()
while [ $# -gt 0 ]; do
    if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
        showUsage
        echo
        echo "Options:"
        echo "  -a, --all       renew all certificates"
        echo "  -v, --verbose   explain what is being done"
        echo "  -q, --quiet     suppress status information"
        echo
        echo "Help options:"
        echo "  -h, --help      display this help and exit"
        echo "      --version   output version information and exit"
        exit 0
    elif [ "$1" == "--version" ]; then
        echo "acme-renew $VERSION ($BUILD)"
        echo "Copyright (c) 2016-2021  Daniel Rudolf"
        echo
        echo "This work is licensed under the terms of the MIT license."
        echo "For a copy, see LICENSE file or <https://opensource.org/licenses/MIT>."
        echo
        echo "Written by Daniel Rudolf <https://www.daniel-rudolf.de/>"
        exit 0
    elif [ "$1" == "--verbose" ] || [ "$1" == "-v" ]; then
        VERBOSE="yes"
    elif [ "$1" == "--quiet" ] || [ "$1" == "-q" ]; then
        # pipe stdout to /dev/null
        exec 1> /dev/null
    elif [ "$1" == "--all" ] || [ "$1" == "-a" ]; then
        while IFS="" read -r -u 4 -d $'\0' DOMAIN; do
            DOMAINS+=( "$DOMAIN" )
        done 4< <(find /etc/ssl/acme/live/ -mindepth 1 -printf "%f\0")
    else
        DOMAINS+=( "$1" )
    fi

    shift
done

if [ ${#DOMAINS[@]} -eq 0 ]; then
    echo "$APP_NAME: You must either pass --all or a DOMAIN_NAME" >&2
    showUsage
    exit 1
fi

EXIT_CODE=0
if [ "$VERBOSE" == "yes" ]; then
    for DOMAIN in "${DOMAINS[@]}"; do
        echo "Renewing '$DOMAIN'..."
        acme-issue --renew "$DOMAIN" || { EXIT_CODE=$?; true; }
    done

    if [ $EXIT_CODE -ne 0 ]; then
        echo "$APP_NAME: Renewal of one or more domains failed" >&2
    fi
else
    for DOMAIN in "${DOMAINS[@]}"; do
        echo -n "Renewing '$DOMAIN'..."
        acme-issue --renew "$DOMAIN" > /dev/null \
            && { echo " success"; } \
            || { echo " failed"; EXIT_CODE=$?; true; }
    done
fi

exit $EXIT_CODE
